language: java

env:
  global:
    - DEPLOY_KEY=keyservertomcat

addons:
  sonarcloud:
    organization: "seramirezdev"
    token:
      secure: "qBDmSS5tY0TYaXRzD9R55XJ+N36AJAfyNQ0y/XkpwZPyI3vFuk3Hb37RmK3174xzFKUy9xJDBDC8nyqd19GJnT6HxdXKh11QLtmJy2Bm5TndAbyfuPQVJG2S0c0H6T63bD+dtsRV/uiFJdP6q9icN3hPdrfVvk2MNlS9p5nk2XjZTebi5hrSKv2MXYrwwd6snzdFqzCuzDMGvreBUU5ZNVv2cVYYuhJIVh9O2qf8Gi33Y0S0aOSrxlCzWjWx2xsWku7iqQkMQcV5OOsvIAO/0WyQzIV6kDjk1wBsQCnKc087WPJFzvxkD0yQdWh8oVNVgsxo/h1ZWnSCX/9dxjui+Q2kkJAiEPHMo9rbIHe5zzgel9jbJzLPUiZfzFOJ+f4D31zj9NdARVPTrZAbmkYXZeMfC8k6P1H/3Y9CWnt2yfyjqFHY95hlIklhtMMwd9VPZJTHwb0sG5SdJZahdy5mHJwC9Dfl5c8PYI/C7RJFn2J77f3S4TwfU/0buQOENnNgabWN6hkvGFT4RKtXDu9tX1SHWFfHUf3ySUurT2hOh5InI/KLuZ1bv3D0waunfiGSLFCJJbAUKMSSmbTY/vEvVNRmsuoXXT4NHb1jR6XgAqu2zex8j3PX7cpsGWVQAwAl2IibOoGufVoth4WFxHbBT1NaKHB1QDaPZqTtO0b4/HY="

script:
  - ./gradlew sonarqube

before_deploy:
  - ssh-keyscan -t rsa -H $HOST_IP >> ${TRAVIS_HOME}/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_7f45f662eb7c_key -iv $encrypted_7f45f662eb7c_iv -in $DEPLOY_KEY.enc -out /tmp/$DEPLOY_KEY -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/$DEPLOY_KEY
  - ssh-add /tmp/$DEPLOY_KEY

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: development

after_deploy:
  - ssh-add -D /tmp/$DEPLOY_KEY
  - rm /tmp/$DEPLOY_KEY
