language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_7f45f662eb7c_key -iv $encrypted_7f45f662eb7c_iv -in keyservertomcat.enc -out /tmp/keyservertomcat -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/keyservertomcat
  - ssh-add /tmp/keyservertomcat

before_deploy:
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $HOST_IP 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts

deploy:
  provider: script
  script: ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: development
