language: java

env:
  global:
    - DEPLOY_KEY=keyservertomcat

before_deploy:
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $HOST_IP 2>&1 | tee -a ${TRAVIS_HOME}/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_7f45f662eb7c_key -iv $encrypted_7f45f662eb7c_iv -in $DEPLOY_KEY.enc -out /tmp/$DEPLOY_KEY -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/$DEPLOY_KEY
  - ssh-add /tmp/$DEPLOY_KEY

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: development

after_deploy:
  - ssh-add -D /tmp/$DEPLOY_KEY
  - rm /tmp/$DEPLOY_KEY