language: java

env:
  global:
    - DEPLOY_KEY=keyservertomcat

addons:
  sonarcloud:
    organization: "seramirezdev"
    token:
      secure: "pN5YPGUj++5RF6KPTj7cGBxOSypVZrIb0AhEoHVvaFMhDt/rI7DuQRxRAWlVVDTZGx6liKeamaIG7YNdn1i+Z2brego5QuHzwHkfO/ie5kEUim2kMH5O3kqvx3sUfKch5RtS1zIc2l7wCT1K16GlX8LGVzAt7kGrWHNsWn8igIw/vRIFvLlEBCAMAAiStHkpnQKXnQs/ZUq5AtnRZ257+FQSP3NbUiDaREXCdvvEpT9xGPHTfnlbBZUT9DeP1XxtSBj4+yj+lticZzm63TNfsnP1QPmdTzQt8SNRRiVoHxTHMPvo+HfizKpyVRALTfpzuXUaq/v0SvoR2+b5cbd6V+Q7iKbpvdKDMe4pXfXrxwt/6mzpfAHghZejrR5N54v9l48WUdsaWEtlnn5r4nlEbWUeMO1v85tecIHXNwvJnEdRTZpSVkB/J+oE4PQzLeE7P81sgOz9gJQ//wEy18Hj7VnoKhhBfSzQyfqGTpxSITQIjXeqSnpn0x91UDGgvFWW/HlBb324RGlSBxyNYLJhw2roVXh6z7mCBGuCwzVYLJYxpbV3PZ/g6BtwlY6Wm/TY6iRrH1eMRaKqjy51dLDwjE7gDoqPpped19KAqoC68zyJKe1zfG3BRElsIdtgmRDiCyAJwYJVP5WLF4J8B9Kg8n8iEueL1kJLHxY8ikKSPV8="

script:
  - ./gradlew sonarqube

cache:
  directories:
    - '$TRAVIS_HOME/.sonar/cache'

before_deploy:
  - ssh-keyscan -t rsa -H $HOST_IP >> ${TRAVIS_HOME}/.ssh/known_hosts
  - openssl aes-256-cbc -K $encrypted_7f45f662eb7c_key -iv $encrypted_7f45f662eb7c_iv -in $DEPLOY_KEY.enc -out /tmp/$DEPLOY_KEY -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/$DEPLOY_KEY
  - ssh-add /tmp/$DEPLOY_KEY

deploy:
  provider: script
  skip_cleanup: true
  script: bash ./scripts/deploy.sh
  on:
    branch: development

after_deploy:
  - ssh-add -D /tmp/$DEPLOY_KEY
  - rm /tmp/$DEPLOY_KEY
