language: java

before_install:
  - openssl aes-256-cbc -K $encrypted_7f45f662eb7c_key -iv $encrypted_7f45f662eb7c_iv -in keyseminariogcp.enc -out /tmp/keyseminariogcp -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/keyseminariogcp
  - ssh-add /tmp/keyseminariogcp

deploy:
  provider: script
  script: bash ./scripts/deploy.sh
  skip_cleanup: true
  on:
    branch: development

